import type { Metadata } from 'next';
import { Bricolage_Grotesque, Manrope } from 'next/font/google';
import './globals.css';
import ReactLenis from 'lenis/react';
import Navigation from '@/components/sections/navigation';

const bricolageGrotesque = Bricolage_Grotesque({
	variable: '--font-bri-sans',
	subsets: ['latin'],
});

const manrope = Manrope({
	variable: '--font-manrope-mono',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body className={`${bricolageGrotesque.variable} ${manrope.variable} antialiased`}>
				<ReactLenis
					root
					options={{
						lerp: 0.1,
						duration: 1.4,
					}}
				>
					<>
						<Navigation />
					</>
					{children}
				</ReactLenis>
			</body>
		</html>
	);
}
